modLoader = "javafml"
loaderVersion = "[39,)"
#issueTrackerURL = ""
license = "LGPL-2.1 License"

[[mods]]
modId = "createchunkloading"
version = "${version}"
displayName = "Create Chunkloading"
authors = "embeddedt"
description = '''
Provides a chunkloader block that works with Create contraptions.
'''
#logoFile = ""

[[dependencies.createchunkloading]]
modId = "forge"
mandatory = true
versionRange = "[47.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createchunkloading]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createchunkloading]]
modId = "architectury"
mandatory = true
versionRange = "[3.7.22,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.createchunkloading]]
modId="create"
mandatory=true
versionRange="[0.5.1,)" #keep updated
ordering="NONE"
side="BOTH"